

name = "coco"
license = "MIT"
licenselink = ""
description = " Thanks to @dirkolbrich @budparr & @dirkolbrich"
homepage = ""
tags = ["Hugo", "Tailwindcss", "theme", "starter"]
features = []
min_version = "0.68"

[author]
  name = "Surikken"
  homepage = "https://github.com/shurikken/"


